<?php $helper = $this->helper('MGS\Social\Helper\Data'); ?>
<?php if($helper->getConfig('instagram_setting/enable_instagram')): ?>
	<?php $images = $this->getWidgetInstagramData() ?>
	<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
	<?php $lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load'); ?>
	<?php $baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank.png'); ?>

	<?php 
		ini_set('default_socket_timeout', 900);
		
		$access_token = $helper->getConfig('instagram_setting/access_token');  
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, "https://api.instagram.com/v1/users/self?access_token={$access_token}");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_HEADER, 0);
		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
		$content = curl_exec($ch);
		curl_close($ch);
		$data = json_decode($content, true);
	?>
	<div class="content-block instagram-block">
			<div class="content-heading">
				<?php if($this->getData('mgs_panel_title')): ?>
					<h3 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h3>
				<?php endif ?>
				<?php if($this->getData('mgs_panel_note')): ?>
					<div class="block-note"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
				<?php endif ?>
				<?php if(isset($data['data'])): ?>
					<h5 class="name hidden"><?php if($data['data']['username']){ echo '@'.$data['data']['username'];}?></h5>
				<?php endif; ?>
			</div>
		
		<?php if(count($images)>0): ?>
			<?php 
				$blockId = rand() . time();
				$useSlider = $this->getUseSlider();
				$perRow = $this->getPerrow(); 
				if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1){
					$columnCount = $perRow * $this->getNumberRow();
				}
				$col = $themeHelper->convertPerRowtoCol($perRow);
				$autoPlay = $this->getAutoplay() ? 'true' : 'false';
				$stopAuto = $this->getStopAuto() ? 'true' : 'false';
				$nav = $this->getNavigation() ? 'true' : 'false';
				$dot = $this->getPagination() ? 'true' : 'false';
			?>
			<?php if($useSlider): ?>
				<div id="instagram-widget<?php echo $blockId ?>" class="owl-carousel">
					<?php $i=0; $j=0; foreach($images as $image): $i++; ?>
						<?php if($this->hasData('number_row') && $this->getNumberRow()>1): ?>
							<?php if ($j++ % $columnCount == 0): ?>
								<div class="item row">
							<?php endif ?>
						<?php endif ?>
						
						<div <?php if($this->getNumberRow()>1): ?>class="multiple-row margin-bottom30 <?php echo $themeHelper->getClearClass($perRow, $i) ?> <?php echo $themeHelper->convertColClass($col, 'col') ?>"<?php endif ?>>
							<div class="instagram-item">
								<?php if($this->getLink()): ?>
									<a href="<?php echo $image['link'] ?>" target="_blank">
								<?php endif ?>
									<?php if(!$lazyLoad): ?>
										<?php $baseImage = $image['src']; ?>
									<?php endif ?>
									<img class="img-responsive<?php if($lazyLoad): ?> owl-lazy<?php endif ?>" src="<?php echo $baseImage ?>" data-src="<?php echo $image['src'] ?>" alt=""/>
								
								<?php if($this->getLink()): ?>
									</a>
								<?php endif ?>
								
								<?php if($this->getLike() || $this->getComment()): ?>
									<span class="social-count">
										<?php if($this->getLike()): ?>
											<span class="like-count"><span class="fa fa-heart-o"></span><span class="number"><?php echo $image['like'] ?></span></span>
										<?php endif ?>
										
										<?php if($this->getComment()): ?>
											<span class="comment-count"><span class="fa fa-comments-o"></span><span class="number"><?php echo $image['comment'] ?></span></span>
										<?php endif ?>
									</span>
								<?php endif ?>
							</div>
						</div>
						<?php if($this->hasData('number_row') && $this->getNumberRow()>1): ?>
							<?php if ($j % $columnCount == 0 || $j == count($images)): ?>
								</div>
							<?php endif ?>
						<?php endif ?>
					<?php endforeach ?>
				</div>
				<?php if($this->hasData('number_row') && $this->getNumberRow()>1):?>
					<?php $perRow = 1; ?>
				<?php endif ?>
				<script type="text/javascript">
					require([
						'jquery',
						'mgs/owlcarousel'
					], function ($) {
						var owlinstagram<?php echo $blockId ?> = $('#instagram-widget<?php echo $blockId ?>').owlCarousel({
							items: <?php echo $perRow; ?>,
							autoplay: <?php echo $autoPlay ?>,
							autoplayHoverPause: <?php echo $stopAuto ?>,
							nav: <?php echo $nav ?>,
							dots: <?php echo $dot ?>,
							<?php if($lazyLoad): ?>lazyLoad: true,<?php endif ?>
							loop: true,
							autoHeight: true,
							navText: ["<i class='pe-7s-angle-left'></i>","<i class='pe-7s-angle-right'></i>"],
							<?php if(!$this->hasData('number_row') || $this->getNumberRow()==1):?>
								responsive:{
									0:{
										items:2
									},
									480:{
										items:4
									},
									768: {
										items:4
									},
									992:{
										items:<?php echo $perRow; ?>
									}
								}
							<?php endif ?>
						});
					});
				</script>
			<?php else: ?>
				<div class="block-content">
					<ul class="row">
						<?php foreach($images as $image): ?>
							<li class="margin-bottom30 col-md-<?php echo $col ?> col-sm-3 col-xs-6">
								<div class="instagram-item">
									<?php if($this->getLink()): ?>
										<a href="<?php echo $image['link'] ?>" target="_blank">
									<?php endif ?>
									
										<?php if(!$lazyLoad): ?>
											<?php $baseImage = $image['src']; ?>
										<?php endif ?>
										<img class="img-responsive<?php if($lazyLoad): ?> lazy<?php endif ?>" src="<?php echo $baseImage ?>" data-src="<?php echo $image['src'] ?>" alt=""/>
									
									<?php if($this->getLink()): ?>
										</a>
									<?php endif ?>
									
									<?php if($this->getLike() || $this->getComment()): ?>
										<span class="social-count">
											<?php if($this->getLike()): ?>
												<span class="like-count"><span class="fa fa-heart"> </span> <span class="number"><?php echo $image['like'] ?></span></span>
											<?php endif ?>
											
											<?php if($this->getComment()): ?>
												<span class="comment-count"><span class="fa fa-comment"> </span> <span class="number"><?php echo $image['comment'] ?></span></span>
											<?php endif ?>
										</span>
									<?php endif ?>
								</div>
							</li>
						<?php endforeach ?>
					</ul>
				</div>
			<?php endif ?>

		<?php else: ?>
			<div role="alert" class="alert alert-warning"><?php echo __('Can not get Instagram data or your instagram account have not any images.') ?></div>
		<?php endif ?>
	</div>
<?php endif ?>